name: Pull Request
description: Feature related issues in the development of the pipeline.
title: "[PR] <title>"
labels: ["Bug fix","New Feature","Breaking change"]
body:
- type: checkboxes
  attributes:
    label: Is there an existing PR for this?
    description: Please search to see if a PR already exists for the change suggested.
    options:
    - label: I have searched for existing PRs
      required: true
- type: checkboxes
  attributes:
    label: Types of changes:
    description: Please select the appropiate type(s) of changes your PR introduces. Select all the boxes that apply.
    options:
    - label: Bug fix (non-breaking change which fixes an issue)
      required: false
    - label: New feature (non-breaking change which adds functionality)
      required: false
    - label: Breaking change (fix or feature that would cause existing functionality to change)
      required: false
    - label: Requires project's documentation update.
      required: false
- type: textarea
  attributes:
    label: Description
    description: Please include a brief summary of the PR. List any dependencies required for this change, if there are any.
  validations:
    required: false      
- type: textarea
  attributes:
    label: Related to / Depends on
    description: List of related issues (`#ISSUE-NUMBER`) or PRs.
  validations:
    required: false      